# Form implementation generated from reading ui file 'ui/view_recipe.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewDialog(object):
    def setupUi(self, ViewDialog):
        ViewDialog.setObjectName("ViewDialog")
        ViewDialog.resize(750, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(ViewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=ViewDialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.imageLabel = QtWidgets.QLabel(parent=ViewDialog)
        self.imageLabel.setMinimumSize(QtCore.QSize(350, 250))
        self.imageLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.imageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout.addWidget(self.imageLabel)
        self.labelIngredientsTitle = QtWidgets.QLabel(parent=ViewDialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelIngredientsTitle.setFont(font)
        self.labelIngredientsTitle.setObjectName("labelIngredientsTitle")
        self.verticalLayout.addWidget(self.labelIngredientsTitle)
        self.tableIngredients = QtWidgets.QTableWidget(parent=ViewDialog)
        self.tableIngredients.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableIngredients.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableIngredients.setObjectName("tableIngredients")
        self.tableIngredients.setColumnCount(3)
        self.tableIngredients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableIngredients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIngredients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableIngredients.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableIngredients)
        self.labelCalories = QtWidgets.QLabel(parent=ViewDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCalories.setFont(font)
        self.labelCalories.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCalories.setObjectName("labelCalories")
        self.verticalLayout.addWidget(self.labelCalories)
        self.btnEdit = QtWidgets.QPushButton(parent=ViewDialog)
        self.btnEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout.addWidget(self.btnEdit)
        self.btnClose = QtWidgets.QPushButton(parent=ViewDialog)
        self.btnClose.setMinimumSize(QtCore.QSize(0, 40))
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)

        self.retranslateUi(ViewDialog)
        QtCore.QMetaObject.connectSlotsByName(ViewDialog)

    def retranslateUi(self, ViewDialog):
        _translate = QtCore.QCoreApplication.translate
        ViewDialog.setWindowTitle(_translate("ViewDialog", "Просмотр рецепта"))
        self.labelIngredientsTitle.setText(_translate("ViewDialog", "Состав блюда (ингредиенты):"))
        item = self.tableIngredients.horizontalHeaderItem(0)
        item.setText(_translate("ViewDialog", "Ингредиент"))
        item = self.tableIngredients.horizontalHeaderItem(1)
        item.setText(_translate("ViewDialog", "Вес (г)"))
        item = self.tableIngredients.horizontalHeaderItem(2)
        item.setText(_translate("ViewDialog", "Ккал/100г"))
        self.btnEdit.setText(_translate("ViewDialog", "Редактировать рецепт"))
        self.btnClose.setText(_translate("ViewDialog", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewDialog = QtWidgets.QDialog()
    ui = Ui_ViewDialog()
    ui.setupUi(ViewDialog)
    ViewDialog.show()
    sys.exit(app.exec())
